name: Win32Service build
on:
  push:
    branches: [ v1.1.x ]
    tags:
      - v1.**
      - 1.**
  pull_request:
    branches: [ v1.1.x ]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: make draft release
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          opt='--prerelease'
          if [[ $v =~ "^v?[0-9]+\.[0-9]+\.[0-9]+$" ]] ; then
            opt='--latest'
          fi
          gh release create ${{ github.ref_name }} --draft --generate-notes --repo win32service/win32service --verify-tag $opt

      - id: set-matrix
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo 'matrix={"php-rel":["8.1", "8.2", "8.3", "8.4", "8.5"], "platform":["x64", "x86"], "ts":["ts", "nts"]}' >> $GITHUB_OUTPUT
          else
            echo 'matrix={"php-rel":["8.5"], "platform":["x64"], "ts":["nts"]}' >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup-matrix
    name: Build
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    outputs:
      repo_tag_name: ${{ steps.install.outputs.repo_tag_name }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set commit in source code
        shell: powershell
        if: ${{ !startsWith(github.ref, 'refs/tags') }}
        run: |
          $version = "${{ github.sha }}"
          Write-Host "Update version to: $version"
          $filePath = "php_win32service.h"
          (Get-Content $filePath) -replace '(PHP_WIN32SERVICE_VERSION\s+)"[^"]+"', ('$1' + "`"$version`"") | Set-Content $filePath
          Write-Host "File $filePath updated."
      - name: Set version in source code
        shell: powershell
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace '^v', ''
          Write-Host "Update version to: $version"
          $filePath = "php_win32service.h"
          (Get-Content $filePath) -replace '(PHP_WIN32SERVICE_VERSION\s+)"[^"]+"', ('$1' + "`"$version`"") | Set-Content $filePath
          Write-Host "File $filePath updated."
      - name: Extract Version
        shell: powershell
        run: |
          chcp 65001
          $r = Select-String -Path php_win32service.h -Pattern 'PHP_WIN32SERVICE_VERSION\s+"([^"]+)"'
          $s = $r.Matches[0].Groups[1]
          $extension_version = 'EXTENSION_VERSION=' + $s.value
          echo $extension_version >> $env:GITHUB_ENV
          echo $extension_version
      - name: Setup PHP
        id: setup-php
        uses: php/setup-php-sdk@e2ce1c294f272ed93e8083f14649f5adadf93788 # v0.12
        with:
          version: ${{matrix.php-rel}}
          arch: ${{matrix.platform}}
          ts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@368ef7d1ee4d1171b31d4a7f67f4d954f903f5a9 # v4
        with:
          arch: ${{matrix.platform}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: Generate Build Files
        run: phpize
      - name: Configure Build
        run: configure --enable-win32service --with-prefix=${{steps.setup-php.outputs.prefix}}
      - name: Build
        run: nmake
      - name: Define Module Env
        shell: powershell
        run: |
          chcp 65001

          $dir = (Get-Location).Path + '\'
          if ('x64' -eq '${{matrix.platform}}') { $dir = $dir + 'x64\' }
          $dir = $dir + 'Release'
          if ('ts' -eq '${{matrix.ts}}') { $dir = $dir + '_TS' }

          ("[php] `nextension=$dir\php_win32service.dll") | Set-Content $env:SystemRoot\php.ini

          $artifact_name = 'php_win32service-${{env.EXTENSION_VERSION}}-${{matrix.php-rel}}'

          if ('ts' -eq '${{matrix.ts}}') { $artifact_name = $artifact_name + '-ts' }
          if ('nts' -eq '${{matrix.ts}}') { $artifact_name = $artifact_name + '-nts' }

          if ('8.0' -eq '${{matrix.php-rel}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.1' -eq '${{matrix.php-rel}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.2' -eq '${{matrix.php-rel}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.3' -eq '${{matrix.php-rel}}') { $artifact_name = $artifact_name + '-vs16' }
          if ('8.4' -eq '${{matrix.php-rel}}') { $artifact_name = $artifact_name + '-vs17' }
          if ('8.5' -eq '${{matrix.php-rel}}') { $artifact_name = $artifact_name + '-vs17' }

          if ('x64' -eq '${{matrix.platform}}') { $artifact_name = $artifact_name + '-x86_64' }
          if ('x86' -eq '${{matrix.platform}}') { $artifact_name = $artifact_name + '-x86' }

          $extension_artifact_name = "ARTIFACT_NAME=" + $artifact_name
          echo $extension_artifact_name >> $env:GITHUB_ENV

          $from = $dir + '\php_win32service.dll'
          $fromDll = $dir+'\'+$artifact_name+'.dll'
          Copy-Item $from $fromDll

          $to = $dir+'\'+$artifact_name+".zip"
          Compress-Archive $fromDll $to
          
          $extension_artifact_archive = "ARTIFACT_ARCHIVE=" + $to
          echo $extension_artifact_archive >> $env:GITHUB_ENV
      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
            name: ${{env.ARTIFACT_NAME}}
            path: ${{env.ARTIFACT_ARCHIVE}}
            
      - name: Create new user
        run: |
          net user subuser p@ssw0rd /add
      - name: test
        shell: powershell
        run: |
          chcp 65001
          sc delete WindowsServicePhpTest
          sc delete WindowsServicePhpTestRun
          mkdir c:\tests_tmp
          $env:TEST_PHP_JUNIT = "c:\junit.out.xml"
          nmake test TESTS="-c null -q --offline --show-diff --show-slow 1000 --set-timeout 120 -g FAIL,XFAIL,BORK,WARN,LEAK,SKIP --temp-source c:\tests_tmp --temp-target c:\tests_tmp"
          
#      - name: Publish Binaries to Release
#        if: ${{ startsWith(github.ref, 'refs/tags') }}
#        uses: svenstaro/upload-release-action@v2
#        with:
#            asset_name: ${{env.ARTIFACT_NAME}}.zip
#            file: ${{env.ARTIFACT_ARCHIVE}}
  check_artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    needs: build
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        if: github.event_name != 'pull_request'
        with:
          merge-multiple: true
          
      - name: Display structure of downloaded files
        if: github.event_name != 'pull_request'
        run: ls -R

      - name: Generate build provenance attestation
        # It does not make sense to do this for PR builds, nor do contributors
        # have permission to do. We can't write attestations to `php/pie` in an
        # unprivileged context, otherwise anyone could send a PR with malicious
        # code, which would store attestation that `php/pie` built the binaries,
        # and it would look genuine. So this should NOT run for PR builds.
        if: github.event_name != 'pull_request'
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4
        with:
          subject-path: 'php_win32service-*.zip'

      - name: Upload all artifacts
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.ref_name }} php_win32service-*.zip --clobber  --repo win32service/win32service
