name: Win32Sample GitHub Release
on:
  push:
    branches: [ v1.0.x ]
  pull_request:
    branches: [ v1.0.x ]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    outputs:
      repo_tag_name: ${{ steps.install.outputs.repo_tag_name }}
    env:
      PHP_BUILD_CACHE_BASE_DIR: c:\build-cache
      PHP_BUILD_OBJ_DIR: c:\obj
      PHP_BUILD_CACHE_SDK_DIR: c:\build-cache\sdk
      PHP_BUILD_SDK_BRANCH: php-sdk-2.2.0
      SDK_REMOTE: https://github.com/Microsoft/php-sdk-binary-tools.git
      SDK_BRANCH: php-sdk-2.2.0
      
      PHP_REL: '8.0'
      ZTS_STATES: enable disable
      PHP_BUILD_CRT: vs16

      PLATFORM: x64

      CFLAGS: /W1 /WX
    steps:
      - uses: actions/checkout@v2
      
      - name: ls
        shell: cmd
        run: dir "C:\Program Files (x86)\Microsoft Visual Studio\"

      - id: install
        name: Install
        shell: cmd
        run: call .\.github\install.cmd

      - name: Build Binary
        env:
          APPVEYOR_REPO_TAG_NAME: ${{ outputs.repo_tag_name }}
        shell: cmd
        run: call .\.github\build.cmd

      - name: config
        shell: cmd
        run: cd /d C:\projects\php-src && cmd /c buildconf.bat --force

      - name: config
        shell: cmd
        run: cd /d C:\projects\php-src && cmd /c configure.bat --disable-all --with-mp=auto --enable-cli --!ZTS_STATE!-zts --enable-win32service=shared --enable-object-out-dir=%PHP_BUILD_OBJ_DIR% --with-config-file-scan-dir=%APPVEYOR_BUILD_FOLDER%\build\modules.d --with-prefix=%APPVEYOR_BUILD_FOLDER%\build --with-php-build=%DEPS_DIR%


      - name: make
        shell: cmd
        run: cd /d C:\projects\php-src && nmake /NOLOGO