name: Win32Sample GitHub Release
on:
  push:
    branches: [ v1.0.x ]
  pull_request:
    branches: [ v1.0.x ]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    env:
      PHP_BUILD_CACHE_BASE_DIR: c:\build-cache
      PHP_BUILD_OBJ_DIR: c:\obj
      PHP_BUILD_CACHE_SDK_DIR: c:\build-cache\sdk
      PHP_BUILD_SDK_BRANCH: php-sdk-2.2.0
      SDK_REMOTE: https://github.com/Microsoft/php-sdk-binary-tools.git
      SDK_BRANCH: php-sdk-2.2.0
      
      PHP_REL: 8.0
      ZTS_STATES: enable
      PHP_BUILD_CRT: vs16
    steps:
      - uses: actions/checkout@v2
          
      - name: Build Binary
        shell: cmd
        run: call .\appveyor\install.cmd
