name: Win32Service build
on:
  push:
    branches: [ v1.0.x ]
    tags:
      - v1.**
  pull_request:
    branches: [ v1.0.x ]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    outputs:
      repo_tag_name: ${{ steps.install.outputs.repo_tag_name }}
    strategy:
      fail-fast: false
      matrix:
        php-rel: ['8.0', '8.1', '8.2']
        platform: [x64, x86]
    env:
      PHP_BUILD_CACHE_BASE_DIR: c:\build-cache
      PHP_BUILD_OBJ_DIR: c:\obj
      PHP_BUILD_CACHE_SDK_DIR: c:\build-cache\sdk
      PHP_BUILD_SDK_BRANCH: 'php-sdk-2.2.0'
      SDK_REMOTE: https://github.com/Microsoft/php-sdk-binary-tools.git
      SDK_BRANCH: 'php-sdk-2.2.0'

      PHP_REL: ${{ matrix.php-rel }}
      ZTS_STATES: enable disable
      PHP_BUILD_CRT: vs16

      PLATFORM: ${{ matrix.platform }}

      CFLAGS: /W1 /WX

    steps:
      - uses: actions/checkout@v3

      - id: install
        name: Install
        shell: cmd
        run: call .\.github\install.cmd

      - name : machine echo steps
        env:
          CONTENT: "${{ toJson(steps) }}"
        shell: cmd
        run: echo %CONTENT%

      - name: Build Binary
        env:
          APPVEYOR_REPO_TAG_NAME: ${{ env.repotagname }}
        shell: cmd
        run: call .\.github\build.cmd

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./artifacts
          name: php_win32service-${{ env.repotagname }}-${{ matrix.platform }}-${{ matrix.php-rel }}

      - name: Run tests
        shell: cmd
        run: call .\.github\test.bat

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/*.dll
          asset_name: php_win32service-${{ env.repotagname }}-${{ matrix.platform }}-${{ matrix.php-rel }}
          tag: ${{ github.ref }}
          file_glob: true
